apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-fpm-deployment
  labels:
    app: php-fpm
spec:
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      app: php-fpm
  template:
    metadata:
      labels:
        app: php-fpm
    spec:
      containers:
      - name: php-fpm
        image: josemanuel10/php-fpm:latest
        ports:
        - containerPort: 9000
