apiVersion: v1
kind: Service
metadata:
  name: php-fpm
spec:
  selector:
    app: php-fpm
  ports:
    - protocol: TCP
      port: 9000         # Puerto expuesto públicamente
      targetPort: 9000   # Puerto del contenedor (containerPort)
